# Generated by Django 2.2.1 on 2019-11-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leaveapprovalcomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveavail',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveavail',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveavail',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
