# Generated by Django 2.2.1 on 2020-01-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20191205_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavemaster',
            name='compensate_able',
        ),
        migrations.AddField(
            model_name='leavemaster',
            name='compensateable',
            field=models.BooleanField(default=False, help_text='Is the leave is compensateable with other leave?'),
        ),
    ]
