# Generated by Django 2.2.1 on 2020-01-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_auto_20200101_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemaster',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
