# Generated by Django 2.2.1 on 2020-01-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_auto_20200101_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavegroup',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
