# Generated by Django 2.2.1 on 2020-01-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_auto_20200101_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemaster',
            name='sandwich_leave_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
