# Generated by Django 2.2.1 on 2020-01-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_auto_20200101_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveremaining',
            name='leave_avail_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaveremaining',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
