# Generated by Django 2.2.1 on 2020-01-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_auto_20200102_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveremaining',
            name='leave_avail_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
