# Generated by Django 2.2.1 on 2020-01-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_auto_20200106_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveentry',
            name='reason_of_leave',
            field=models.TextField(blank=True, null=True),
        ),
    ]
