# Generated by Django 2.2.1 on 2020-01-16 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_auto_20200116_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveremaining',
            old_name='leave_avail_date',
            new_name='leave_expired_date',
        ),
    ]
