# Generated by Django 2.2.1 on 2020-01-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0012_auto_20200116_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveremaining',
            name='availing_in_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
