# Generated by Django 2.2.1 on 2020-01-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0013_leaveremaining_availing_in_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveremaining',
            name='availing_in_seconds',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
