# Generated by Django 2.2.1 on 2020-01-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_auto_20200116_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveremaining',
            name='availing_in_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
