# Generated by Django 2.2.1 on 2020-01-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0015_auto_20200116_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavegroupsettings',
            name='fractional_duration',
            field=models.IntegerField(blank=True, default=0, verbose_name='Leave Duration'),
        ),
    ]
