# Generated by Django 2.2.1 on 2020-02-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0016_auto_20200129_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavegroupsettings',
            name='employee_can_apply',
            field=models.BooleanField(default=False, verbose_name='Restriction for employee can apply'),
        ),
    ]
