# Generated by Django 2.2.1 on 2019-11-20 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_rolehierarchy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee',
        ),
    ]
