# Generated by Django 2.2.1 on 2019-11-20 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20191119_1316'),
        ('user_management', '0003_remove_user_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.EmployeeIdentification'),
        ),
    ]
