# Generated by Django 2.2.1 on 2020-01-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('user_management', '0005_workflow_workflowapproval_workflownotificationrecipient_workflowvariation_workflowvariationinitiator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflownotificationrecipient',
            name='notification_recipient',
        ),
        migrations.AddField(
            model_name='workflownotificationrecipient',
            name='notification_recipient',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
