# Generated by Django 2.2.1 on 2020-02-17 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_jobinformation_status'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_management', '0006_auto_20200121_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.UUIDField()),
                ('item_type', models.CharField(blank=True, choices=[('late-entry', 'Late Entry'), ('early-out', 'Early Out'), ('leave', 'Leave')], max_length=10)),
                ('operator', models.CharField(blank=True, max_length=3, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('reporting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.EmployeeIdentification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
