# Generated by Django 2.2.1 on 2020-02-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='item',
            field=models.IntegerField(),
        ),
    ]
