# Generated by Django 2.2.1 on 2020-02-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_jobinformation_status'),
        ('user_management', '0009_auto_20200224_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='ApprovalNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.EmployeeIdentification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
