# Generated by Django 2.2.1 on 2020-02-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0010_auto_20200224_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard',
            field=models.CharField(choices=[('employee', 'Employee'), ('management', 'Management'), ('admin', 'Admin')], max_length=10, null=True),
        ),
    ]
