# Generated by Django 2.2.1 on 2020-03-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0011_user_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='self_panel',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
