# Generated by Django 2.2.1 on 2019-11-28 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20191120_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressandcontact',
            name='permanent_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_city', to='setting.Cities', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='addressandcontact',
            name='permanent_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_country', to='setting.Countries', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='addressandcontact',
            name='permanent_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_state', to='setting.States', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='addressandcontact',
            name='present_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prensent_city', to='setting.Cities', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='addressandcontact',
            name='present_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prensent_country', to='setting.Countries', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='addressandcontact',
            name='present_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prensent_state', to='setting.States', verbose_name='State'),
        ),
    ]
