# Generated by Django 2.2.1 on 2019-12-01 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20191128_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressandcontact',
            name='permanent_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_city', to='setting.Cities', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='addressandcontact',
            name='permanent_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_country', to='setting.Countries', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='addressandcontact',
            name='permanent_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_state', to='setting.States', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='place_of_birth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.Countries'),
        ),
        migrations.AlterField(
            model_name='professionalcertificate',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.Countries'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.Cities'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.Countries'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.States'),
        ),
        migrations.AlterField(
            model_name='training',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.Countries'),
        ),
    ]
