# Generated by Django 2.2.1 on 2019-12-30 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20191208_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarystructure',
            name='salary_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.SalaryGroup'),
        ),
    ]
