# Generated by Django 2.2.1 on 2020-01-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20200114_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeidentification',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
