# Generated by Django 2.2.1 on 2020-01-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20200115_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeidentification',
            name='employee_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
