# Generated by Django 2.2.1 on 2020-01-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_auto_20200115_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressandcontact',
            name='present_thana',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Thana'),
        ),
    ]
