# Generated by Django 2.2.1 on 2020-01-15 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_auto_20200115_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endofcontract',
            name='date_of_settlement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endofcontract',
            name='due_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endofcontract',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endofcontract',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.EmployeeIdentification'),
        ),
    ]
