# Generated by Django 2.2.1 on 2020-01-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_auto_20200115_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retirement',
            name='date_of_settlement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retirement',
            name='due_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retirement',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
