# Generated by Django 2.2.1 on 2020-01-15 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_auto_20200115_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='calendar_master',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_calendar', to='attendance.CalendarMaster', verbose_name='Calendar'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='schedule_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.ScheduleMaster'),
        ),
        migrations.AlterField(
            model_name='leavemanage',
            name='deduction_group',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_leave_deduction', to='payroll.DeductionGroup'),
        ),
        migrations.AlterField(
            model_name='leavemanage',
            name='leave_group',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.LeaveGroup'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='employee_bank_name',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.Bank'),
        ),
    ]
