# Generated by Django 2.2.1 on 2020-02-06 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_auto_20200113_1814'),
        ('employees', '0017_auto_20200115_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinformation',
            name='branch',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_branch', to='setting.Branch'),
        ),
    ]
