# Generated by Django 2.2.1 on 2020-02-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_jobinformation_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinformation',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
