# Generated by Django 2.2.1 on 2020-02-24 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_jobinformation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_employee', to='employees.EmployeeIdentification'),
        ),
    ]
