# Generated by Django 2.2.1 on 2020-03-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_auto_20200224_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='confirmation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobinformation',
            name='date_of_offer',
            field=models.DateField(blank=True, null=True),
        ),
    ]
