from employees.views.master.employee_master import *
from employees.views.master.employee_salary_info import *
from employees.views.master.employee_personal_info import *
from employees.views.master.employee_contact_info import *
from employees.views.master.employee_family_info import *
from employees.views.master.employment_history import *
from employees.views.master.em_reference import *
from employees.views.master.em_asset import *
from employees.views.master.em_education import *
from employees.views.master.skill import *
from employees.views.master.document import *
from employees.views.master.attendance_leave import *
