from django.contrib import admin
from .models import *

admin.site.register(EmployeeIdentification)
admin.site.register(JobInformation)
admin.site.register(Employment)
admin.site.register(EndOfContract)
admin.site.register(Separation)
admin.site.register(Retirement)
admin.site.register(Payment)
admin.site.register(SalaryStructure)
admin.site.register(Personal)
admin.site.register(AddressAndContact)
admin.site.register(EmergencyContact)
admin.site.register(Family)
admin.site.register(Education)
admin.site.register(Skill)
admin.site.register(Training)
admin.site.register(ProfessionalCertificate)
admin.site.register(LanguageProficiency)
admin.site.register(EmploymentHistory)
admin.site.register(Reference)
admin.site.register(Asset)
admin.site.register(Documents)
admin.site.register(OthersDocuments)
admin.site.register(Attendance)
admin.site.register(LeaveManage)
