# Generated by Django 2.2.1 on 2019-11-19 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cimbolic', '0008_auto_20191013_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsentSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no_of_absent', models.IntegerField(blank=True, default=0)),
                ('condition_type', models.CharField(blank=True, choices=[('rule-based', 'Rule Based'), ('variable', 'Variable'), ('manual-entry', 'Manual Entry')], default='rule-based', max_length=20)),
                ('basis_type', models.CharField(blank=True, choices=[('day-basis', 'Day Basis'), ('salary-basis', 'On Top of Salary')], default='day-basis', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BonusComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('short_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('bonus_period', models.CharField(choices=[('year', 'Year'), ('half-year', 'Half Year'), ('quarter', 'Quarter'), ('month', 'Month')], default='year', max_length=20)),
                ('bonus_frequency', models.IntegerField(blank=True, null=True)),
                ('rule_type', models.CharField(blank=True, choices=[('rule-based', 'Rule Based'), ('variable', 'Variable')], default='rule-based', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BonusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('short_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BonusGroupComponentMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('short_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], default='earning', max_length=20)),
                ('is_gross', models.BooleanField(blank=True, default=False)),
                ('is_taxable', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeductionComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('short_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('deduction_component_type', models.CharField(choices=[('absent', 'Absent'), ('late', 'Late'), ('early-out', 'Early Out'), ('under-work', 'Under-work'), ('other', 'Other')], default='absent', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeductionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('short_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EarlyOutSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('early_out_allowed_time', models.IntegerField(blank=True, default=0)),
                ('early_out_allowed_time_unit', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour')], default='minute', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EarlyOutSlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour')], default='minute', max_length=20)),
                ('condition_type', models.CharField(blank=True, choices=[('rule-based', 'Rule Based'), ('variable', 'Variable'), ('manual-entry', 'Manual Entry')], default='rule-based', max_length=20)),
                ('basis_type', models.CharField(blank=True, choices=[('day-basis', 'Day Basis'), ('salary-basis', 'On Top of Salary')], default='day-basis', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('disbursed_date', models.DateTimeField(blank=True, null=True)),
                ('net_earning', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_earning', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('with-held', 'With-Held'), ('disbursed', 'Disbursed')], default='draft', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeVariableSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition_type', models.CharField(blank=True, choices=[('rule-based', 'Rule Based'), ('variable', 'Variable'), ('mapped', 'Mapped with Other Component'), ('manual-entry', 'Manual Entry')], default='rule-based', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LateSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('late_grace_time', models.IntegerField(blank=True, default=0)),
                ('late_grace_time_unit', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour')], default='minute', max_length=20)),
                ('late_last_time', models.IntegerField(blank=True, default=0)),
                ('late_last_time_unit', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour')], default='minute', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LateSlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour')], default='minute', max_length=20)),
                ('condition_type', models.CharField(blank=True, choices=[('rule-based', 'Rule Based'), ('variable', 'Variable'), ('manual-entry', 'Manual Entry')], default='rule-based', max_length=20)),
                ('basis_type', models.CharField(blank=True, choices=[('day-basis', 'Day Basis'), ('salary-basis', 'On Top of Salary')], default='day-basis', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('max_range', models.FloatField(default=0.0)),
                ('min_range', models.FloatField(default=0.0)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consolidate', models.BooleanField(blank=True, default=False)),
                ('payment_type', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Cheque', 'Cheque')], default='Cash', max_length=10)),
                ('payment_frequency', models.CharField(blank=True, choices=[('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Monthly', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('short_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnderWorkSlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.IntegerField(blank=True, default=0)),
                ('unit', models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour')], default='minute', max_length=20)),
                ('condition_type', models.CharField(blank=True, choices=[('rule-based', 'Rule Based'), ('variable', 'Variable'), ('manual-entry', 'Manual Entry')], default='rule-based', max_length=20)),
                ('basis_type', models.CharField(blank=True, choices=[('day-basis', 'Day Basis'), ('salary-basis', 'On Top of Salary')], default='day-basis', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('component', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.DeductionComponent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryGroupComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition_type', models.CharField(blank=True, choices=[('rule-based', 'Rule Based'), ('variable', 'Variable'), ('mapped', 'Mapped with Other Component'), ('manual-entry', 'Manual Entry')], default='rule-based', max_length=20)),
                ('mapping_policy', models.CharField(choices=[('overtime', 'Overtime'), ('absent', 'Absent'), ('late', 'Late'), ('under-work', 'Under Work'), ('early-out', 'Early Out'), ('bonus', 'Bonus')], default='overtime', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Component')),
                ('salary_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.SalaryGroup')),
                ('variable', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cimbolic.Variable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='salarygroup',
            name='component',
            field=models.ManyToManyField(through='payroll.SalaryGroupComponent', to='payroll.Component'),
        ),
        migrations.CreateModel(
            name='SalaryBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Component')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Salary')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='salary',
            name='component',
            field=models.ManyToManyField(through='payroll.SalaryBreakdown', to='payroll.Component'),
        ),
        migrations.CreateModel(
            name='PaySlipComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.BooleanField(default=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeVariableSalary')),
                ('employee_salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeSalary')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
