# Generated by Django 2.2.1 on 2019-11-19 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cimbolic', '0008_auto_20191013_2347'),
        ('payroll', '0002_auto_20191119_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuscomponent',
            name='variable',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cimbolic.Variable'),
        ),
    ]
