# Generated by Django 2.2.1 on 2019-11-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_underworkslabrbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='lateslab',
            name='days_to_consider',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
