# Generated by Django 2.2.1 on 2019-11-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_lateslab_days_to_consider'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlyoutslab',
            name='days_to_consider',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='underworkslab',
            name='days_to_consider',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
