# Generated by Django 2.2.1 on 2019-11-20 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
        ('payroll', '0009_auto_20191120_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslipcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip_component', to='payroll.EmployeeVariableSalary'),
        ),
        migrations.CreateModel(
            name='SalaryPaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_mode', models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('fintech', 'Fintech'), ('mixed', 'Mixed')], max_length=20, null=True)),
                ('employee_salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payment_method', to='payroll.EmployeeSalary')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentDisbursedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_bank_AC_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Employee Bank A/C Name')),
                ('bank_branch_code', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_AC_no', models.IntegerField(blank=True, null=True, verbose_name='Bank A/C No')),
                ('routing_number', models.CharField(blank=True, max_length=255, null=True)),
                ('cheque_number', models.IntegerField(null=True)),
                ('fintech_service', models.CharField(choices=[('bkash', 'bkash'), ('rocket', 'Rocket'), ('upay', 'Upay'), ('nagad', 'Nagad'), ('mcash', 'mCash'), ('dmoney', 'Dmoney'), ('other', 'Other')], max_length=20, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=255, null=True)),
                ('disbursed_amount', models.IntegerField(null=True)),
                ('employee_bank_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setting.Bank')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disburse_payment_method', to='payroll.SalaryPaymentMethod')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
