# Generated by Django 2.2.1 on 2019-11-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_auto_20191120_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdisbursedinfo',
            name='payment_mode',
            field=models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('fintech', 'Fintech')], max_length=20, null=True),
        ),
    ]
