# Generated by Django 2.2.1 on 2019-11-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_paymentdisbursedinfo_payment_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdisbursedinfo',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='paymentdisbursedinfo',
            name='payment_mode_for_mixed',
            field=models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('fintech', 'Fintech')], max_length=20, null=True, verbose_name='Payment Mode'),
        ),
    ]
