# Generated by Django 2.2.1 on 2019-11-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_auto_20191121_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdisbursedinfo',
            name='disbursed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
