# Generated by Django 2.2.1 on 2019-11-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_auto_20191121_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdisbursedinfo',
            name='cheque_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdisbursedinfo',
            name='fintech_service',
            field=models.CharField(blank=True, choices=[('bkash', 'bkash'), ('rocket', 'Rocket'), ('upay', 'Upay'), ('nagad', 'Nagad'), ('mcash', 'mCash'), ('dmoney', 'Dmoney'), ('other', 'Other')], max_length=20, null=True, verbose_name='Select Service'),
        ),
        migrations.AlterField(
            model_name='paymentdisbursedinfo',
            name='payment_mode_for_mixed',
            field=models.CharField(blank=True, choices=[('bank', 'Bank'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('fintech', 'Fintech')], max_length=20, null=True, verbose_name='Payment Mode'),
        ),
    ]
