# Generated by Django 2.2.1 on 2019-11-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leaveapprovalcomment_user'),
        ('payroll', '0013_auto_20191121_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_seconds', models.IntegerField(default=0)),
                ('notes', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('avail_leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.LeaveMaster')),
                ('employee_salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeSalary')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
