# Generated by Django 2.2.1 on 2019-11-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_auto_20191121_2035'),
        ('payroll', '0014_leavededuction'),
    ]

    operations = [
    ]
