# Generated by Django 2.2.1 on 2019-11-25 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_merge_20191122_1443'),
        ('payroll', '0015_merge_20191121_2039'),
    ]

    operations = [
    ]
