# Generated by Django 2.2.1 on 2019-11-26 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_merge_20191125_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipcomponent',
            name='condition_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payslipcomponent',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.Component'),
        ),
    ]
