# Generated by Django 2.2.1 on 2020-02-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_auto_20191126_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarybreakdown',
            name='component',
        ),
        migrations.RemoveField(
            model_name='salarybreakdown',
            name='salary',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.DeleteModel(
            name='SalaryBreakdown',
        ),
    ]
