# Generated by Django 2.2.1 on 2020-01-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_delete_employeebankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalstructure',
            name='order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
