# Generated by Django 2.2.1 on 2020-01-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_organizationalstructure_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='physicaladdress',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='physicaladdress',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='virtualaddress',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
