# Generated by Django 2.2.1 on 2019-11-19 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_auto_20191119_1316'),
        ('leave', '0001_initial'),
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lateapprovalcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lateapplication',
            name='attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.AttendanceData'),
        ),
        migrations.AddField(
            model_name='holidaygroupmastermembers',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.HolidayGroup'),
        ),
        migrations.AddField(
            model_name='holidaygroupmastermembers',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.HolidayMaster'),
        ),
        migrations.AddField(
            model_name='holidaygroup',
            name='holiday',
            field=models.ManyToManyField(through='attendance.HolidayGroupMasterMembers', to='attendance.HolidayMaster'),
        ),
        migrations.AddField(
            model_name='flexibletype',
            name='days',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.Days'),
        ),
        migrations.AddField(
            model_name='flexibletype',
            name='schedule_master',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='flexible_schedule', to='attendance.ScheduleMaster'),
        ),
        migrations.AddField(
            model_name='earlyapprovalcomment',
            name='early_out',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='early_out', to='attendance.EarlyApplication'),
        ),
        migrations.AddField(
            model_name='earlyapprovalcomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='earlyapplication',
            name='attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.AttendanceData'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_daily_record', to='employees.EmployeeIdentification'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='leave_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.LeaveMaster'),
        ),
        migrations.AddField(
            model_name='calendarmaster',
            name='holiday_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.HolidayGroup', verbose_name='Select Holiday Group'),
        ),
        migrations.AddField(
            model_name='calendarmaster',
            name='parent_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.CalendarMaster'),
        ),
        migrations.AddField(
            model_name='breaktime',
            name='timetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.TimeTable'),
        ),
        migrations.AddField(
            model_name='attendancedata',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_daily_attendance', to='employees.EmployeeIdentification'),
        ),
        migrations.AddField(
            model_name='attendancebreak',
            name='attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.AttendanceData'),
        ),
    ]
