# Generated by Django 2.2.1 on 2019-11-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20191121_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimewagecalculationrulebased',
            name='basis',
            field=models.CharField(choices=[('m', 'Minutely'), ('h', 'Hourly'), ('d', 'Daily'), ('s', 'Top of salary')], default='h', help_text='Scope type of the wage calculation (per hour, per day etc.)', max_length=1),
        ),
    ]
