# Generated by Django 2.2.1 on 2019-12-08 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20191208_1552'),
        ('attendance', '0005_auto_20191204_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(null=True)),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_holiday', models.BooleanField(default=False)),
                ('is_working_day', models.BooleanField(default=True)),
                ('is_leave', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_daily_record', to='employees.EmployeeIdentification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='is_holiday',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='is_leave',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='is_weekend',
        ),
        migrations.RemoveField(
            model_name='dailyrecord',
            name='is_working_day',
        ),
        migrations.CreateModel(
            name='TimeTableRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('out_date', models.DateField(null=True)),
                ('schedule_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_record_model', to='attendance.ScheduleRecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BreakTimeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('break_start', models.TimeField()),
                ('break_start_date', models.DateField(null=True)),
                ('break_end', models.TimeField()),
                ('break_end_date', models.DateField(null=True)),
                ('timetable_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.TimeTableRecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='schedule_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.ScheduleRecord'),
        ),
    ]
