# Generated by Django 2.2.1 on 2019-12-08 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20191208_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaktime',
            name='timetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breaktime_model', to='attendance.TimeTable'),
        ),
    ]
