# Generated by Django 2.2.1 on 2019-12-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20191208_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerecord',
            name='working_hour',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='schedulerecord',
            name='working_hour_unit',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
