# Generated by Django 2.2.1 on 2019-12-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20191209_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='countable_post_overtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='countable_pre_overtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='breaktimerecord',
            name='break_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breaktimerecord',
            name='break_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breaktimerecord',
            name='break_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breaktimerecord',
            name='break_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetablerecord',
            name='out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
