# Generated by Django 2.2.1 on 2019-12-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20191211_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerule',
            name='segment',
            field=models.CharField(choices=[('pre', 'Pre-work Overtime'), ('post', 'Post-work Overtime'), ('both', 'Both')], default='post', max_length=4, verbose_name='OT segment'),
        ),
    ]
