# Generated by Django 2.2.1 on 2019-12-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20191211_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemaster',
            name='roaster_type',
        ),
        migrations.AddField(
            model_name='schedulemaster',
            name='roster_type',
            field=models.CharField(blank=True, choices=[('fixed-roster', 'Fixed Roster'), ('variable-roster', 'Variable Roster')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='schedule_type',
            field=models.CharField(choices=[('regular-fixed-time', 'Regular Fixed Time'), ('fixed-day', 'Fixed Day'), ('hourly', 'Hourly'), ('weekly', 'Weekly'), ('day', 'Day'), ('freelancing', 'Freelancing'), ('roster', 'Roster'), ('flexible', 'Flexible')], max_length=255, null=True),
        ),
    ]
