# Generated by Django 2.2.1 on 2019-12-11 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_dailyrecord_daily_pre_overtime_seconds'),
        ('attendance', '0010_auto_20191211_1606'),
    ]

    operations = [
    ]
