# Generated by Django 2.2.1 on 2019-12-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_overtimerule_segment'),
        ('attendance', '0011_merge_20191211_1722'),
    ]

    operations = [
    ]
