# Generated by Django 2.2.1 on 2019-12-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_merge_20191211_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrecord',
            old_name='daily_overtime_seconds',
            new_name='daily_post_overtime_seconds',
        ),
    ]
