# Generated by Django 2.2.1 on 2019-12-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_auto_20191211_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overtimerule',
            old_name='buffer_duration',
            new_name='buffer_duration_post',
        ),
        migrations.RenameField(
            model_name='overtimerule',
            old_name='buffer_duration_unit',
            new_name='buffer_duration_unit_post',
        ),
        migrations.RenameField(
            model_name='overtimerule',
            old_name='minimum_working_duration',
            new_name='minimum_working_duration_post',
        ),
        migrations.RenameField(
            model_name='overtimerule',
            old_name='minimum_working_duration_unit',
            new_name='minimum_working_duration_unit_post',
        ),
        migrations.RenameField(
            model_name='overtimerule',
            old_name='tolerance_time',
            new_name='tolerance_time_post',
        ),
        migrations.AddField(
            model_name='overtimerule',
            name='buffer_duration_pre',
            field=models.PositiveIntegerField(default=0, help_text='Minimum duration before overtime takes effect'),
        ),
        migrations.AddField(
            model_name='overtimerule',
            name='buffer_duration_unit_pre',
            field=models.CharField(choices=[('m', 'Minute(s)'), ('h', 'Hour(s)')], default='m', max_length=1),
        ),
        migrations.AddField(
            model_name='overtimerule',
            name='minimum_working_duration_pre',
            field=models.PositiveIntegerField(default=1, help_text='Minimum duration to work for overtime to count'),
        ),
        migrations.AddField(
            model_name='overtimerule',
            name='minimum_working_duration_unit_pre',
            field=models.CharField(choices=[('m', 'Minute(s)'), ('h', 'Hour(s)')], default='h', max_length=1),
        ),
        migrations.AddField(
            model_name='overtimerule',
            name='tolerance_time_pre',
            field=models.PositiveIntegerField(default=0, help_text='Helper for rounding the OT duration'),
        ),
    ]
