# Generated by Django 2.2.1 on 2019-12-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_auto_20191218_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimedurationrestriction',
            name='ot_segment',
            field=models.CharField(choices=[('pre', 'For Pre-work Overtime'), ('post', 'For Post-work Overtime')], default='post', max_length=4, verbose_name='OT segment'),
        ),
    ]
