# Generated by Django 2.2.1 on 2020-01-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_auto_20191231_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemaster',
            name='shortcode',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
