# Generated by Django 2.2.1 on 2020-01-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_auto_20200108_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarmaster',
            name='status_value',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='holidaygroup',
            name='short_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='holidaymaster',
            name='short_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
