# Generated by Django 2.2.1 on 2020-01-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_auto_20200115_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarmaster',
            name='status',
        ),
    ]
