# Generated by Django 2.2.1 on 2020-01-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_remove_calendarmaster_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarmaster',
            old_name='status_value',
            new_name='status',
        ),
    ]
