# Generated by Django 2.2.1 on 2020-01-15 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_auto_20200115_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemaster',
            name='status_value',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='calendarmaster',
            name='holiday_group',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.HolidayGroup', verbose_name='Select Holiday Group'),
        ),
    ]
