# Generated by Django 2.2.1 on 2020-01-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_remove_schedulemaster_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulemaster',
            old_name='status_value',
            new_name='status',
        ),
    ]
